version: "3.8"
services:
  streamlit-shaper-api:
    build:
      context: .
    ports:
      - "8522:8522"
    restart: always

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"  # Expose Nginx on port 80 (adjust as needed)
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount custom Nginx configuration
  #     - ./static:/app/static:ro
  #   depends_on:
  #     - streamlit-shaper-api
  #   restart: always
